### ISSUE TITLE
Class Death Knight glyph  [Glyph of Dark Succor]

### ISSUE THREAD

**Issue by Jacksawdk** [WoWMortal/Deathwing-Bug-reports#6]
**Description:**
Describe the bug

**Current behavior:**
What happens

**Expected behavior:**

**Proof/Screenshots:**

**Steps to reproduce the problem:**

1.It doest work well it proc when you kill mobs but it consume runes that's bug.

2.How it shall work.Glyph of Dark Succor. Use: Permanently teaches you this glyph. When you kill an enemy that yields experience or honor, while in Frost or Unholy Presence, your next Death Strike within 15 sec is free and will restore at least 20% of your maximum health.

3.https://cata-twinhead.twinstar.cz/?spell=96279

you should also attach valid link of the related spell from either http://wowhead.com/  to your report

**Additional context**

**Comment by Prince-SH** [comment]
Rejected
