### ISSUE TITLE
Divine Purpose & Zealotry

### ISSUE THREAD

**Issue by Renehadox** [WoWMortal/Deathwing-Bug-reports#86]
**Description:**
Describe the bug

Divine purpose buff should not be consumed when you use Zealotry.

**Current behavior:**
What happens

What it's currently doing: Zealotry consumes Divine Purpose.

**Expected behavior:**

What it should be doing: Zealotry isn't supposed to consume Divine Purpose.

**Proof/Screenshots:**

**Steps to reproduce the problem:**

1.

2.

3.

you should also attach valid link of the related spell from either http://wowhead.com/  to your report

**Additional context**

**Comment by Prince-SH** [comment]
Thanks for your Report.
/Fixed
